services:
  mongo:
    image: mongo:6
    container_name: hotelease-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d
      - mongo_data:/data/db
  
  hotelease-api:
    build: ./crud-api/
    container_name: hotelease-api
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/HotelEase
      - PORT=3000
    depends_on:
      - mongo
    restart: always

  nginx:
    image: nginx:latest
    container_name: hotelease-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - hotelease-api
    restart: always

volumes:
  mongo_data: